"""Create order column association table

Revision ID: 889775ac4d3f
Revises: cb74a0d7d886
Create Date: 2024-09-01 20:36:44.107223
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '889775ac4d3f'
down_revision: Union[str, None] = 'cb74a0d7d886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'order_product_association',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['orders.id'],
        ),
        sa.ForeignKeyConstraint(
            ['product_id'],
            ['products.id'],
        ),
        sa.PrimaryKeyConstraint('id', 'order_id', 'product_id'),
        sa.UniqueConstraint(
            'order_id', 'product_id', name='idx_unique_order_product'
        ),
    )
    op.drop_column('orders', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('price', sa.INTEGER(), nullable=False))
    op.drop_table('order_product_association')
    # ### end Alembic commands ###
